FROM maven:3.6.0-jdk-8
MAINTAINER antazri.xyz

VOLUME [ "/Users/anthony/idea-workspace/LibraryManager-P10/LibraryManager-P10/LibraryManager-WebApp-P10/", "/use/local/LibraryManager-WebApp-P10" ]

RUN cd /usr/local/
RUN ls -a